### PR TITLE
341 v 3+ bug format fix need on clear button

### LINKED ISSUE #341: v 3+ (BUG) format fix need on 'Clear Button'
ToDO:  (as of 12/6 w/ @andaniel2029 / @bestw07 's rebase of the /develop/ branch). 

We need to do the following to the 'Clear' buttons on the 'Add Tree' page.

1) Remove the UPPER right-hand 'Clear' button. This button as of the current release - CLEARS everything including the image.

We will now be using the button above Conifer/Broadleaf. To do this type of Clear 'everything'.

Expected outcome: Only 1 'Clear button' on screen - which is located under the image section and just above the 'Broadleaf' button. Make sure this button 'clears EVERYTHING' (including image) when it is selected. Have a pop-up show up that says : 

'Are you sure?'

Options are:
Cancel    or    Yes, clear all

204118186-260e9bef-41e9-4734-8201-a72148532288

2) Fix the spacing on the Clear button so that it is not overlapping the Broadleaf button. (This image was taken from the iPhone 13 once the checkin happened on 12/5. )
need to fix sizing on clear

### PR DESCRIPTION
**Pull request by mtalhadev**

### CODE REVIEW

**Review by bestw07 — CHANGES_REQUESTED** [review]
First of all, I can see you used the rn-tooltip package. it is new for our repo, so you should include rn-tooltip node_module dependencies and pod modules for it.

For this reason, I got an error when I pull this request.

Thanks.

**Comment by bestw07** [comment]
Screenshot 2022-12-09 at 19 55 56

This screenshot is when I run this PR code.

**Comment by mtalhadev** [comment]
Thankyou for giving a review, I will push it, but I have a major important question, which always had been confusion for me for this project. Why do we push node_modeles and pods, rather than installing them locally, for example for the error you showed, yarn install will fix it.

**Comment by bestw07** [comment]
> Thankyou for giving a review, I will push it, but I have a major important question, which always had been confusion for me for this project. Why do we push node_modeles and pods, rather than installing them locally, for example for the error you showed, yarn install will fix it.

you are welcome and good question.

I know you are an experienced developer and I know how to fix that also.

I said already that it would be better to add node_modules and pod module folder to the git ignore file to @TreeMama  and @halmueller before.

But they wanted to keep it on the repo for non-technical people, so they can clone it and run it directly without installation.

As you know, node_modules relates to the node js version and it causes some errors when the users install it.

For more details, you can ask about that to @TreeMama  and @halmueller , thanks.

**Comment by halmueller** [comment]
Yes that sums it up. I’m not involved with the day to day of the project. But I’m the only one who can do an App Store build. So I want to know for sure that what I’m building from is identical to what you’re building from. We do it the same way at my day job, for the same reason. HalOn Dec 9, 2022, at 5:57 PM, bestw07 ***@***.***> wrote:﻿

Thankyou for giving a review, I will push it, but I have a major important question, which always had been confusion for me for this project. Why do we push node_modeles and pods, rather than installing them locally, for example for the error you showed, yarn install will fix it.

you are welcome and good question.
I know you are an experienced developer and I know how to fix that also.
For node_modules and pod module folder, I recommend adding those to the git ignore file to @TreeMama  and @halmueller before.
But they wanted to keep it on the repo for non-technical people, so they can clone it and run it directly without installation.
As you know, node_modules relates to the node js version and it causes some errors when the users install it.
For more details, you can ask about that to @TreeMama  and @halmueller , thanks.

**Comment by bestw07** [comment]
Hi, @mtalhadev .

I checked your PR, but I still, get errors when I run `yarn ios` command.

Screenshot 2022-12-10 at 04 22 31


Screenshot 2022-12-10 at 04 53 35

**Comment by bestw07** [comment]
I did run `yarn install` and `pod install` command again.

When I run those commands, it showed some added and changed files.

You can check it here, @mtalhadev .

https://github.com/TreeMama/iSeaTree-React-Prototype/pull/354/commits/b7a16bae43d665d0b9614dd0cc6548130f012c9a

Now, build success.

I will check functionalities with @TreeMama .

Thank you.

Screenshot 2022-12-10 at 04 52 17

Screenshot 2022-12-10 at 04 54 29

**Comment by TreeMama** [comment]
hi @mtalhadev - we don't see the functionality for IF TreeBot is on and the species is detected the 'isValidated' filed = 'NEEDS VALIDATION'.

Can you maybe sync up with me to clarify this (it is git issue #331 ?

Otherwise @bestw07 - I think we should commit and @mtalhadev can open another branch based off the updated /develop/ for the #331 use case I mention above.

test

**Review by bestw07 — APPROVED** [review]

**Comment by getweys** [comment]
> Yes that sums it up. I’m not involved with the day to day of the project. But I’m the only one who can do an App Store build. So I want to know for sure that what I’m building from is identical to what you’re building from. We do it the same way at my day job, for the same reason. HalOn Dec 9, 2022, at 5:57 PM, bestw07 ***@***.***> wrote:﻿ Thankyou for giving a review, I will push it, but I have a major important question, which always had been confusion for me for this project. Why do we push node_modeles and pods, rather than installing them locally, for example for the error you showed, yarn install will fix it. you are welcome and good question. I know you are an experienced developer and I know how to fix that also. For node_modules and pod module folder, I recommend adding those to the git ignore file to @TreeMama and @halmueller before. But they wanted to keep it on the repo for non-technical people, so they can clone it and run it directly without installation. As you know, node_modules relates to the node js version and it causes some errors when the users install it. For more details, you can ask about that to @TreeMama and @halmueller , thanks. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Thank you for explaining this, but we can also start teaching them, and asking them to push just package.json file when modules are changed so that on your local machine, on any library install you don't get issues with any library or module. But capicity you guys know better bandwidth of the students.

**Comment by mtalhadev** [comment]
> Yes that sums it up. I’m not involved with the day to day of the project. But I’m the only one who can do an App Store build. So I want to know for sure that what I’m building from is identical to what you’re building from. We do it the same way at my day job, for the same reason. HalOn Dec 9, 2022, at 5:57 PM, bestw07 ***@***.***> wrote:﻿ Thankyou for giving a review, I will push it, but I have a major important question, which always had been confusion for me for this project. Why do we push node_modeles and pods, rather than installing them locally, for example for the error you showed, yarn install will fix it. you are welcome and good question. I know you are an experienced developer and I know how to fix that also. For node_modules and pod module folder, I recommend adding those to the git ignore file to @TreeMama and @halmueller before. But they wanted to keep it on the repo for non-technical people, so they can clone it and run it directly without installation. As you know, node_modules relates to the node js version and it causes some errors when the users install it. For more details, you can ask about that to @TreeMama and @halmueller , thanks. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Thank you for explaining this, but we can also start teaching them, and asking them to push just package.json file when modules are changed so that on your local machine, on any library install you don't get issues with any library or module. But capicity you guys know better bandwidth of the students.

**Pull request merged**
