### PR TITLE
Fix 476 navigator displaying issue

### PR DESCRIPTION
**Pull request by kafkakk**
I didn’t observe any navigator display issues, as depicted in the screenshot on Android. The problem seems to be related to certain older iPhone models, such as the iPhone 8.
I enlarged the size of the navigator on the bottom to address the gap between the navigator and the map(in the map screen).
Tested on the iPhone 8, iPhone 11, and iPhone 14 Pro simulators and Nexus One and Pixel 6 emulators.
Please try to test on your side.

### CODE REVIEW

**Comment by bestw07** [comment]
Hi, Lawrence Zhao.

Did you build it from Mac or Windows system?

**Comment by bestw07** [comment]
Hi @kafkakk .

I uploaded the screenshot of the app.

It looks like there are some gaps.

You can check the red-marked parts.

And I should install the pod module again, that's why I asked which OS did you use for the build.

Also, send a review request to @TreeMama  (Ari) as well.


Screenshot at Aug 10 20-11-38

**Comment by bestw07** [comment]
I pushed my changes (for ios build), @kafkakk .

**Comment by kafkakk** [comment]
@bestw07 I built on macOS

**Comment by kafkakk** [comment]
I see the issue. On my profile, the badges are few, so on my page it looks good. I will fix it.

**Comment by kafkakk** [comment]
Hi, @bestw07. I've acquired sufficient badges to replicate the display issue on your end. I resolved the problem and subsequently reorganized the map layout. I think the map no longer experiences partial coverage by the navigator, as you can see the complete visibility of the Apple logo in the lower left corner. 
And my build was conducted on macOS. Tested on the iPhone 8, iPhone 11, and iPhone 14 Pro simulators and Nexus One and Pixel 6 emulators.

@jgrenadier Jim, can you test on Android?


iShot_2023-08-11_17 10 19

**Comment by bestw07** [comment]
good, thank you for your update, @kafkakk .

Let me pull and test it.

**Comment by bestw07** [comment]
it looks good.

Once Ari @TreeMama confirmed, we can merge it to develop branch.

Screenshot_1691806824

simulator_screenshot_FA0C90FC-6548-43F9-A415-513C00D78DF3

**Review by bestw07 — APPROVED** [review]

**Comment by jgrenadier** [comment]
basic menus look ok on android. Cant test the badge issue since map not displaying.  This is probably just a testing issue but  probably because no map showing, I get an exception after adding a tree.  Screen capture of exception: https://www.dropbox.com/scl/fi/v159079mqyb9rh1vf6c2z/Screenshot_20230811-215036.png?rlkey=qgze8jwx1w4492ldbgqv2v04p&dl=0   I'll try some workarounds tomorrow for more testing.  Again: I think the exception that I saw was related to my test environment and not this code change. More later.

**Pull request merged**
