### PR TITLE
Fixed tutorial page button issue by pr 477

### PR DESCRIPTION
**Pull request by kafkakk**
Fixed the overlaying issue of images and texts on a Nexus One Phone

### CODE REVIEW

**Comment by jgrenadier** [comment]
tested tutorial and looks ok on android. When someone test on apple device or simulator, we can close this.

**Comment by bestw07** [comment]
Hi, @kafkakk.

Did you work on this ticket?

https://github.com/TreeMama/iSeaTree-React-Prototype/issues/477

Let me know, so I can check and review it.

thanks.

**Comment by kafkakk** [comment]
@bestw07 Yes. Ari asked me to offer my assistance in #476 and #477.

**Review by bestw07 — CHANGES_REQUESTED** [review]
@kafkakk needs to work from the latest `develop` branch.

**Pull request closed without merging**
