### PR TITLE
remove two vestigial Expo files

### PR DESCRIPTION
**Pull request by halmueller**

### CODE REVIEW

**Comment by halmueller** [comment]
Please verify that it is safe to remove these two files.

**Comment by halmueller** [comment]
Is `iOS/iSeaTree/Supporting/Expo.plist` still relevant? Or can it be deleted too?

**Review by andaniel2029 — COMMENTED** [review]
Hello, @halmueller.

I build it and test on the mac os Android emulator.

check the below-attached image.

all works.

Screenshot_1639371294

**Comment by halmueller** [comment]
What happens if you delete Expo.list?

Hal Mueller
***@***.***

**Comment by halmueller** [comment]
Duh. Never mind, I can test that bit myself.

**Comment by halmueller** [comment]
Expo.plist _is_ needed in the iOS app. Removing it causes a crash on launch. I don't know why, and I don't care enough to investigate.

**Pull request merged**
