### PR TITLE
Updating master for new build

### PR DESCRIPTION
**Pull request by jyang81**
Doing this with @TreeMama 's approval.

### CODE REVIEW

**Comment by halmueller** [comment]
Do "future you" and "future everyone else" a favor by writing slightly more informative commit messages. In this case, noting which version/build you updated to would be helpful to others reading this commit. For some examples, try "git log app.json".

**Comment by jyang81** [comment]
Sorry, I didn't know what to write for this. I was just asked by @TreeMama to merge develop into master.
Should I just put 'bump to 2.0(37)'?

**Comment by halmueller** [comment]
Yeah, that would have been good. 

In general I try to save myself from having to remember. Commit messages, just like code, are read much more than they’re written. So adding a bit of explaining usually pays for itself, as far as time saved understanding what was done vs time taken to write them. 

Adding a feature or fixing a bug is usually a one-off, and self descriptive: “add support for the gronculator.” But release tasks are repetitive, doing the same thing each release to the same subset of files. I adapt my messages accordingly so that the next person can skim instead of having to read closely.

**Comment by halmueller** [comment]
Changing the title of the PR doesn’t help, btw. You have to catch it when you commit. 

There is a way to go back and fix a commit message. But don’t worry about it, it’s just something to remember for next time.

**Pull request merged**
